config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :charts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_and_belongs_to_many :inputs
  validate :name

  NAMES = %w[ daily_intake
              weekly_hair_growth
              monthly_cycle
              weekly_weight
              weekly_bust
              weekly_waist
              weekly_butt ].freeze
end

app/models/input.rb
class Input < ApplicationRecord
  has_and_belongs_to_many :chart
  COLORS = %w[].freeze
  NAMES  = %w[
              Mushroom Saw_palmetto Shatavari
              Egg Chicken Chicken_feet_stock
              Coconut_oil Mint_tea Parsley
              Salmon Mozzarella Rice Buckwheat
              Oatmilk Spinach Milk Feta Yogurt
              Red_wine
            ].freeze
  validate :name, :quantity, :origin

  #has a name, quantity, origin, color
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
    @chart = Chart.find(params[:id])
    @chart_labels = []
    @chart_data   = []
    @chart_colors = []
    @chart.inputs.each do |input|
      @chart_labels.push(input.name.to_s)
      @chart_data.push(input.quantity)
      @chart_colors.push(input.color)
    end
    #binding.irb
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.fetch(:chart, {})
    end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]

  # GET /inputs
  # GET /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs
  # POST /inputs.json
  def create
    #binding.irb
    @input            = Input.new
    @input.name       = params[:name]
    @input.quantity   = params[:quantity]
    @input.origin     = params[:origin]
    @input.color      = params[:color]
    @input.chart_name = params[:chart_name]
    chart             = Chart.find_by(name: @input.chart_name.to_s)
    chart.inputs.push(@input)
    chart.save

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: 'Input was successfully updated.' }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: 'Input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.fetch(:input, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/charts/_daily_intake.html.erb
<%= javascript_tag do %>
  var chart_labels_pre = [<%= raw @chart_labels.to_json %>];
  var chart_labels = []
  for(var i in chart_labels_pre)
    for(var j in chart_labels_pre[i])
      chart_labels.push(chart_labels_pre[i][j])

  var chart_colors_pre = [<%= raw @chart_colors.to_json %>];
  var chart_colors = []
  for(var i in chart_colors_pre)
    for(var j in chart_colors_pre[i])
      chart_colors.push(chart_colors_pre[i][j])

  var chart_data   = "<%= @chart_data %>";
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'pie',
      data: {
          labels: chart_labels,
          datasets: [{
              data: JSON.parse(chart_data),
              backgroundColor: chart_colors,
              borderColor: [
                'rgba(63, 191, 63, 0.5)',
                'rgba(63, 191, 63, 0.5)'
              ],
              borderWidth: 5
          }]
      },
      options: {
        //cutoutPercentage: 30
      }
  });
</script>

app/views/charts/_form.html.erb
<%= form_with(model: chart, local: true) do |form| %>
  <% if chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charts/_monthly_cycle.html.erb
<%= javascript_tag do %>
  var chart_labels_pre = [<%= raw @chart_labels.to_json %>];
  var chart_labels = []
  for(var i in chart_labels_pre)
    for(var j in chart_labels_pre[i])
      chart_labels.push(chart_labels_pre[i][j])
  var chart_data   = "<%= @chart_data %>";
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: chart_labels,
          datasets: [{
              data: JSON.parse(chart_data),
              backgroundColor: [
                  'rgba(255, 99, 132, 0.5)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)'
              ],
              borderWidth: 5
          }]
      },
      options: {
        cutoutPercentage: 30
      }
  });
</script>

app/views/charts/_weekly_bust.html.erb
<%= javascript_tag do %>
  var chart_labels_pre = [<%= raw @chart_labels.to_json %>];
  var chart_labels = []
  for(var i in chart_labels_pre)
    for(var j in chart_labels_pre[i])
      chart_labels.push(chart_labels_pre[i][j])
  var chart_data   = "<%= @chart_data %>";
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: chart_labels,
          datasets: [{
              data: JSON.parse(chart_data),
              backgroundColor: [
                  'rgba(255, 99, 132, 0.5)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)'
              ],
              borderWidth: 5
          }]
      },
      options: {
        cutoutPercentage: 30
      }
  });
</script>

app/views/charts/_weekly_hair_growth.html.erb
<%= javascript_tag do %>
  var chart_labels_pre = [<%= raw @chart_labels.to_json %>];
  var chart_labels = []
  for(var i in chart_labels_pre)
    for(var j in chart_labels_pre[i])
      chart_labels.push(chart_labels_pre[i][j])
  var chart_data   = "<%= @chart_data %>";
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: chart_labels,
          datasets: [{
              data: JSON.parse(chart_data),
              backgroundColor: [
                  'rgba(255, 99, 132, 0.5)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)'
              ],
              borderWidth: 5
          }]
      },
      options: {
        cutoutPercentage: 30
      }
  });
</script>

app/views/charts/_weekly_waist.html.erb
<%= javascript_tag do %>
  var chart_labels_pre = [<%= raw @chart_labels.to_json %>];
  var chart_labels = []
  for(var i in chart_labels_pre)
    for(var j in chart_labels_pre[i])
      chart_labels.push(chart_labels_pre[i][j])
  var chart_data   = "<%= @chart_data %>";
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: chart_labels,
          datasets: [{
              data: JSON.parse(chart_data),
              backgroundColor: [
                  'rgba(255, 99, 132, 0.5)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)'
              ],
              borderWidth: 5
          }]
      },
      options: {
        cutoutPercentage: 30
      }
  });
</script>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>World population</title>
  </head>
  <body>
    <div class="wrapper">
      <h1><%= @chart.name %></h1>
      <h2>Graphical Representation of Nutrient Intake, averaged by Number of Days</h2>
      Days: x
      <canvas id="myChart" width="1600" height="900"></canvas>

      <%= render "#{@chart.name}" %>
    </div>
  </body>
</html>

app/views/inputs/_form.html.erb
<%= form_with(model: input, local: true) do |form| %>
  <% if input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

app/views/inputs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inputs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inputs.each do |input| %>
      <tr>
        <td><%= link_to 'Show', input %></td>
        <td><%= link_to 'Edit', edit_input_path(input) %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path %>

app/views/inputs/new.html.erb
<h1>New Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Back', inputs_path %>

app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChartsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>